# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER vctgo

# 挂载目录
VOLUME /home/vctgo
# 创建目录
RUN mkdir -p /home/vctgo
# 指定路径
WORKDIR /home/vctgo
# 复制jar文件到路径
COPY ./jar/vctgo-auth.jar /home/vctgo/vctgo-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","vctgo-auth.jar"]
