# 基础镜像
FROM nginx
# author
MAINTAINER vctgo

# 挂载目录
VOLUME /home/vctgo/projects/vctgo-ui
# 创建目录
RUN mkdir -p /home/vctgo/projects/vctgo-ui
# 指定路径
WORKDIR /home/vctgo/projects/vctgo-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/vctgo/projects/vctgo-ui
